kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 3000
    targetPort: http-server
    nodePort: 30305
  selector:
    app: guestbook
  type: NodePort
